import type { Metadata } from "next";
import "./globals.css";

import { Open_Sans, Titillium_Web } from "next/font/google";
import Nav from "@/components/Nav";

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-open-sans",
});

const titilliumWeb = Titillium_Web({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-titillium-web",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${titilliumWeb.variable} antialiased`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
